FROM node:10-alpine as builder

# install and cache app dependencies
COPY ./web_framework/client_side/package.json ./web_framework/client_side/package-lock.json ./
RUN npm install --only=prod&& mkdir /react-frontend && mv ./node_modules ./react-frontend

WORKDIR /react-frontend

COPY ./web_framework/client_side .

RUN REACT_APP_IS_PRODUCTION=1 npm run build 
